# Generated by Django 2.2.6 on 2019-10-22 07:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todos', '0002_write_like_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_like_users',
            field=models.ManyToManyField(related_name='comment_like_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
